### ISSUE TITLE
TermRef rendering toggle highlighting

### ISSUE THREAD

**Issue by maaikevanleuken** [essif-lab/framework#155]
Enabling the reader to choose whether they want to see the highlighting of terminology defined in the glossary or not, for readability purposes. A solution could be to have something like a 'show references / show no references' toggle button, such as a 'Dutch / English' toggle or 'dark mode / light mode' toggle.

**Comment by RieksJ** [comment]
Different readers have different ideas about what they want to see in terms of term-ref rendering. There are various options possible for highlighting (bolding, coloring), creating a popup, linking to the curated text, that may be independently configurable at runtime (that is: for the reader, in a way that resembles how the reader can choose between dark/light mode). For example, only do the option for the first occurrence of a term, or for all occurrences. Readers may want to choose the 'only the first' option for highlighting, but not for popup and/or linking. Other combinations are conceivable as well.

Obviously, it has to be considered how that would work in combination with different rendering systems (Docusaurus, gh-pages, PDFs, etc.).

Let's use this issue to 
- collect different wishes that users/readers have expressed
- register (im)possibilities of various rendering systems

So that with this information, we can write the specs for this enahncement.

**Comment by RieksJ** [comment]
The TEv2 tools (currently) facilitate this as follows:

1. Call the HRGT from some input file that contains an MRGEntry marker(s), to create HRGs (output files). 
2. Call the TRRT for only these HRGs (output files), specifying the converter that produces the highlighting and other stuff as you like.

A prerequisite is that the file that is input for the HRGT SHOULD NOT contain any TermRefs of the same syntax as the TermRefs that will exist within the converted MRGEntry, unless they would need to be highlighted in the same way.
